baseURL = "https://www.danweaver.dev"
languageCode = "en-us"
title = "danweaver.devÔ∏è"
theme = "snf"

# Header
[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

# Footer
[[menu.footer]]
        name = "Github"
        url = "https://github.com/jgoggles"
        weight = 1 
